services:
  database:
    image: 'postgres:17'
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local
