server:
  port: 8080

spring:
  application:
    name: hackit
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hackit_db}
    username: admin
    password: admin
  flyway:
    schemas:
      - public
      - hackit_db
  jpa:
    hibernate.ddl-auto: validate
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

jwt:
  private-key: classpath:jwt/app.key
  public-ke y: classpath:jwt/app.pub
  ttl: 15m

email-verification:
  base-url: http://localhost:8080/api/auth/email/verify?uid=%s&t=%s
  required: true

otp:
  email-verification:
    cache-prefix: otp:email-verification:%s
    ttl: 5m
    characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
    length: 50