name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: Generate JWT keys for tests
        run: |
          mkdir -p src/main/resources/jwt
          mkdir -p src/test/resources/jwt
          openssl genrsa -out src/main/resources/jwt/app.key 2048
          openssl rsa -in src/main/resources/jwt/app.key -pubout -out src/main/resources/jwt/app.pub
          openssl genrsa -out src/test/resources/jwt/test.key 2048
          openssl rsa -in src/test/resources/jwt/test.key -pubout -out src/test/resources/jwt/test.pub
          ls -la src/main/resources/jwt/
          ls -la src/test/resources/jwt/

      - name: Build and test
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew clean test -x spotlessCheck -x checkstyleMain -x checkstyleTest --no-daemon --debug
      
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/
          retention-days: 7
