name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: hackit_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d hackit_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -U postgres -d hackit_db; do
            echo "Waiting for Postgres…"
            sleep 1
          done
      
      - name: Check code formatting
        run: ./gradlew spotlessCheck --no-daemon || echo "Code formatting check failed"
      
      - name: Generate formatting report
        if: always()
        run: ./gradlew spotlessCheck --no-daemon || true

      - name: Build, test and lint
        env:
          SPRING_DATASOURCE_URL:    jdbc:postgresql://localhost:5432/hackit_db
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: admin
        run: ./gradlew clean check --no-daemon

      - name: Run checkstyle with detailed report
        if: always()
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon

      - name: Generate Spotless formatting report
        if: always()
        run: ./gradlew spotlessCheck --no-daemon || true
        
      - name: Upload checkstyle reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-reports
          path: |
            build/reports/checkstyle/
          retention-days: 7
      
      - name: Upload spotless reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: spotless-reports
          path: |
            build/reports/spotless/
          retention-days: 7
      
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            build/reports/tests/
          retention-days: 7
