name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: hackit_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.POSTGRES_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -U "${{ secrets.POSTGRES_USER }}" -d hackit_db; do
            echo "Waiting for Postgres…"
            sleep 1
          done

      - name: Build, test and lint
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/hackit_db
          SPRING_DATASOURCE_USERNAME: ${{ secrets.POSTGRES_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: ./gradlew clean check --no-daemon

      - name: Tear down services
        if: always()
        run: echo "Services will be automatically torn down by Actions"
